openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: wabli-bme-1
  url: https://83.212.100.226:4001/v1
security:
- {}
tags:
- description: not yet ready
  name: welcome
paths:
  /welcome:
    post:
      operationId: createwelcome
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/welcome'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/welcome'
          description: successful operation
      summary: Creates the data
      tags:
      - welcome
      x-eov-operation-handler: controllers/WelcomeController
  /welcome/{welcomeId}:
    delete:
      operationId: deletewelcome
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: welcomeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - welcome
      x-eov-operation-handler: controllers/WelcomeController
    get:
      operationId: getwelcome
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: welcomeId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/welcome'
          description: successful operation
      summary: Get the element
      tags:
      - welcome
      x-eov-operation-handler: controllers/WelcomeController
    put:
      operationId: updatewelcome
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: welcomeId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/welcome'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/welcome'
          description: successful operation
      summary: Updates the element
      tags:
      - welcome
      x-eov-operation-handler: controllers/WelcomeController
  /welcome/getAll:
    get:
      operationId: getAllwelcome
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/welcome'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - welcome
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/WelcomeController
  /welcome/getByParams:
    get:
      operationId: getByParamswelcome
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/welcome'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - welcome
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/WelcomeController
components:
  schemas:
    welcome:
      example:
        welcomeTitle: welcomeTitle
        _id: _id
      properties:
        _id:
          type: string
        welcomeTitle:
          type: string
      required:
      - welcomeTitle
      type: object
