openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: wabli-bme-1
  url: https://83.212.100.226:4001/v1
security:
- {}
tags:
- description: not yet ready
  name: wev
paths:
  /wev:
    post:
      operationId: createwev
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wev'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wev'
          description: successful operation
      summary: Creates the data
      tags:
      - wev
      x-eov-operation-handler: controllers/WevController
  /wev/{wevId}:
    delete:
      operationId: deletewev
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: wevId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - wev
      x-eov-operation-handler: controllers/WevController
    get:
      operationId: getwev
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: wevId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wev'
          description: successful operation
      summary: Get the element
      tags:
      - wev
      x-eov-operation-handler: controllers/WevController
    put:
      operationId: updatewev
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: wevId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/wev'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wev'
          description: successful operation
      summary: Updates the element
      tags:
      - wev
      x-eov-operation-handler: controllers/WevController
  /wev/getAll:
    get:
      operationId: getAllwev
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/wev'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - wev
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/WevController
  /wev/getByParams:
    get:
      operationId: getByParamswev
      parameters:
      - description: the query based on which the search is performed
        explode: true
        in: query
        name: filter
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/wev'
                type: array
          description: successful operation
      summary: Get all the data based on user query
      tags:
      - wev
      x-method-get-by-params: "true"
      x-eov-operation-handler: controllers/WevController
components:
  schemas:
    wev:
      example:
        tile: tile
        _id: _id
      properties:
        _id:
          type: string
        tile:
          type: string
      required:
      - tile
      type: object
